print("python strict indentation")
print(r'//\\||')
print(r"\\//||")
print(r"\'hello's")
print('\'hello')
strn="a \n \" string in new line and escape double quote with back\ slash"
print(strn + " concatenation")
print(strn.isupper())
print(strn.upper().isupper())
print(len(strn))
print(strn[-1])
print(strn[6:10])
print(strn[6:])
print(strn[:10])
print(strn.index("i"))
print(strn.index("string"))
print(strn.replace("escape","AESCAP"))
print(strn)
print(10-3+2*4/6)
print(2*3+5)
print(2*(3+5))
num = 10%4
print(num)
#print(num+"hey") this will give error type mismatch
print(str(num)+"Hey")
